export const invoiceSymbolAliasMap = {
  NUCO: ['NU HOLDINGS LTD'],
  ECOPETROL: ['ECOPETROL'],
  TERPEL: ['ORGANIZACION TER', 'ORGANIZACION TERPEL'],
  ISA: ['ISA INTERCONEXIO', 'INTERCONEXION ELECTRICA'],
  CEMARGOS: ['CEMENTOS ARGOS A', 'CEMENTOS ARGOS'],
  GEB: ['GRUPO ENERGIA BO', 'EMPR ENERG DE BGTA', 'EMPRESA DE ENERGI'],
  GRUPOARGOS: ['GRUPO ARGOS S A', 'AO GRUPO ARGOS GRUPO ARGOS S A', 'GRUPO ARGOS'],
  GRUPOSURA: ['GRUPOSURA', 'GRUPO DE INV SURAME', 'GRUPO DE INVERSI', 'ACCION ORD GRUPO DE INV SURAME'],
  PFCIBEST: ['PREFERE GRUPO CIBEST', 'PREFERENCIAL GRUPO CIBEST', 'ACCION PREFERE GRUPO CIBEST'],
  CIBEST: ['GRUPO CIBEST SA', 'ACCION ORD GRUPO CIBEST', 'ORD GRUPO CIBEST'],
  EXITO: ['EXITO'],
} as const

export type InvoiceMappedSymbol = keyof typeof invoiceSymbolAliasMap
