export const ANALYTICS_REALTIME_REFETCH_MS = 60_000
export const ANALYTICS_REALTIME_STALE_MS = 60_000
export const ANALYTICS_REALTIME_GC_MS = 15 * 60_000
export const ANALYTICS_SNAPSHOT_LIMIT = 2
export const ANALYTICS_ZSCORE_LIMIT = 500
export const ANALYTICS_DAILY_CLOSING_LIMIT = 5_000
